name: Transverse CI

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: db_docker_symfony
        ports:
          - 3306:3306
        # wait for db
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      # ubuntu latest have php 8.1 preinstalled and app require 8.2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Setup composer
        working-directory: ./project
        run: |
          composer install --ignore-platform-req=php

      - name: Setup DATABASE_URL in .env
        working-directory: ./project
        run: sed -i '' 's|echo "DATABASE_URL=.*|echo "DATABASE_URL=mysql://root:root@127.0.0.1:3306/db_docker_symfony?serverVersion=5.7&charset=utf8mb4" >> .env

      - name: Setup DB
        working-directory: ./project
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "DROP DATABASE IF EXISTS db_transverse_test"
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE db_transverse_test"

      - name: Load fixtures
        working-directory: ./project
        run: |
          php bin/console d:m:m --no-interaction --env=test
          php bin/console d:f:l --no-interaction --env=test

      - name: Run tests
        working-directory: ./project
        run: php bin/phpunit
