name: PHPStan Analysis

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --no-scripts --no-progress --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon
