name: PHPStan Analysis

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install
        working-directory: project

      - name: Run PHPStan
        run: php ./project/vendor/bin/phpstan analyse --configuration=phpstan.neon
        # working-directory: project
