name: Update Version from .env

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install
        working-directory: project

      - name: Read version from composer.json
        id: read-version
        run: |
          VERSION=$(jq -r .version composer.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Git tag
        if: env.VERSION != ''
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
